### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by bonyhardian** [adamfilipczyk/FirstWords#1]
Hi bro,

Can I use your code for my project?
I need your permission.
Please check this: https://choosealicense.com/licenses/mit/

Thanks,
Bony

**Comment by adamfilipczyk** [comment]
Hi Bony,

Yeah, go ahead. You can use any part of the code except the sounds

Good luck
Adam

**Comment by bonyhardian** [comment]
Hi Adam,

Thank you very much for your permission.

Regards,
Bony
